title: "My project 2025"
author: "Leonardo Rodovero"
email: "s240095@student.dtu.dk"
description: "A minimal Jekyll site"
theme: minima

# If you prefer a minimal layout, you can remove or comment out the theme line
# theme: minima

# If you used a "docs" folder, ensure baseurl is empty or set correctly
baseurl: "" 
url: "http://localhost:4000"  # For local preview. GitHub Pages can override this.
