title: "Social Data Stories"
description: "Exploring social data visualizations."
author: "Leonardo Rodovero"
email: "s240095@student.dtu.dk"
theme: minima  # or another GitHub-supported theme
baseurl: ""    # if your site is at <username>.github.io, keep this blank
url: ""        # GitHub Pages will figure out the final URL automatically
plugins:
  - jekyll-feed   # Example plugin if you want an RSS feed
  # Add others as needed
  - jemoji
theme: jekyll-theme-midnight
